export { ParticleSystem } from './core/ParticleSystem';
export type { ParticleSystemConfig } from './core/ParticleSystem';
export { Particle } from './core/Particle';
export type { IBehavior } from './behaviors/IBehavior';
export { FollowMouseBehavior } from './behaviors/FollowMouseBehavior';
export { GravityBehavior } from './behaviors/GravityBehavior';
export { RepulseBehavior } from './behaviors/RepulseBehavior';
export { MagneticFieldBehavior } from './behaviors/MagneticFieldBehavior';
export { VortexBehavior } from './behaviors/VortexBehavior';
export { WaveBehavior } from './behaviors/WaveBehavior';
export { ExplosionBehavior } from './behaviors/ExplosionBehavior';
export { Renderer } from './rendering/Renderer';
export { ConfigLoader } from './loaders/ConfigLoader';
export type { ParticleConfig } from './loaders/ConfigLoader';